/*
 * THE DOCUMENTATION TAB, LOADED WHEN IT IS OPENED.
 *
 * Three hundred lines of prose shipped in the first chunk to everybody, including the great majority who
 * never open the tab. It is the one part of the planner that is text rather than arithmetic or controls,
 * so it is the one part that can leave the first load without anything else changing: App renders it
 * through React.lazy, and this file has no state of its own beyond the section list it reports back.
 *
 * Everything the prose quotes - the plan, the parameters, the trial counts, the money formatter - comes
 * in as props, so this module imports nothing from App.jsx and cannot pull the engine into a second
 * chunk. The copy editor (vite-plugin-inline-edit) scans this file alongside App.jsx, so the text here
 * stays editable in place.
 */
import { useEffect } from 'react';
import { Zap, Sliders, ShieldCheck, Wallet, Trophy, Plus, HelpCircle, Gift, Dices, Coins, BookOpen } from 'lucide-react';
import { PhoneCollapse } from './phone.jsx';
import { Term as T } from './glossary.jsx';

export default function Docs({ E, P, plan, nmpa, terminalAge, activeRiskMatrix, isPhone, docSections, onSections,
  scrollToDocSection, MC_TRIALS, TOURNAMENT_TRIALS, SHOW_INHERITANCE, formatGBP, fmtNum }) {
  /*
   * The contents list is read off the rendered cards rather than kept as a second hand-written list: a
   * new card joins the contents by itself, and one that stops leading with a heading goes visibly
   * missing rather than quietly dropping out of a list nobody re-checks. It runs here, after this
   * chunk has rendered, because an effect in App would fire before the cards existed.
   */
  useEffect(() => {
    const found = [...document.querySelectorAll('[id^="doc-"]')]
      .map(el => { const h = el.querySelector('h2'); return h ? { id: el.id, label: h.textContent.trim() } : null; })
      .filter(Boolean);
    onSections(found);
  }, [onSections]);
  return (
    <div className="space-y-6">
      {!isPhone && docSections.length > 1 && (
        <nav data-doc-contents aria-label="Documentation contents" className="bg-surface border border-slate-200/90 p-5 rounded-xl">
          <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><BookOpen className="w-4 h-4 text-blue-600" /> What is in here</h2>
          <ol className="mt-2.5 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-x-6 gap-y-0.5 text-xs">
            {docSections.map((sec, i) => (
              <li key={sec.id} className="flex gap-2 items-baseline">
                <span className="text-slate-400 tabular-nums shrink-0">{i + 1}</span>
                <button type="button" onClick={() => scrollToDocSection(sec.id)}
                  className="text-left min-h-6 text-blue-700 hover:text-blue-900 hover:underline font-semibold cursor-pointer">{sec.label}</button>
              </li>
            ))}
          </ol>
        </nav>
      )}
      <div id="doc-mc-buttons" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><Dices className="w-4 h-4 text-blue-600" /> The Three Stages of a <T k="Monte Carlo">Monte Carlo</T> Run</h2>
        <p className="text-xs text-slate-600 leading-relaxed">Two of these run from one button on the Projection tab, each result appearing as its stage finishes. They use the same engine on the same {fmtNum(MC_TRIALS)} randomised market paths and differ only in which side of the equation is held fixed: one fixes your spending and reports the risk, the other fixes the risk and reports the spending. The second can be switched off if you only want the fast answer. The third leaves both alone and changes where the money sits instead; it answers a different question, so it has its own tab and its own button.</p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-lg space-y-1">
            <strong className="text-slate-800 block">Stage 1, always runs: is the plan solvent?</strong>
            <p className="text-slate-500">Takes the target living expenditure from Plan Inputs exactly as entered and runs it through {fmtNum(MC_TRIALS)} paths. The answer is a <strong>survival rate</strong>: the share of paths that funded every year to age {terminalAge} without running dry and finished above your bequest floor. Use it once you know roughly what you want to spend. This stage reports a probability rather than targeting one, so the target survival rate does not affect it.</p>
          </div>
          <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-lg space-y-1">
            <strong className="text-slate-800 block">Stage 2, optional: "how much could I spend?"</strong>
            <p className="text-slate-500">Ignores your target figure and solves for the <strong>largest annual spend</strong> that still survives at the target survival rate you pick. It bisects on the spending amount, re-running the full simulation at each step, which is why it takes longer than the first stage. At 95% it finds the spend that fails in no more than 1 path in 20. Because it describes a different spend from the one you entered, it gets its own line in the verdict and its own row of figures, rather than overwriting stage 1.</p>
          </div>
          <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-lg space-y-1">
            <strong className="text-slate-800 block">The target survival rate (85 / 90 / 95%)</strong>
            <p className="text-slate-500">Only affects stage 2. It is the share of paths you are asking the spending figure to survive, so a <em>lower</em> target returns a <em>higher</em> figure: 85% buys you more income now in exchange for a 1-in-7 chance of running short. 95% is the conventional planning benchmark. Changing it after a run offers to solve stage 2 again on its own, since nothing else depends on it.</p>
          </div>
          <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-lg space-y-1">
            <strong className="text-slate-800 block">On the Strategy tab: "would a different split do better?"</strong>
            <p className="text-slate-500">Holds your spending and your budget fixed and re-splits the budget between wrappers, scoring each strategy on identical market paths. It is the slowest stage because it runs several full simulations, and two of its players search a range of candidates first. The methodology and the players are documented below.</p>
          </div>
        </div>
        <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-lg space-y-1 text-xs">
          <strong className="text-slate-800 block">One expected path, two ranges</strong>
          <p className="text-slate-500">Stage 1 keeps every simulated path, not just its ending, so the chart can show where all {fmtNum(MC_TRIALS)} of them stood at each age: the shaded band is the 10th to 90th percentile, the solid line the median. Read the right-hand edge and you get the same three pot figures reported underneath it, because both use the same quantile. No path follows any of the three lines, and the band widens with age because nothing cancels out the early years.</p>
          <p className="text-slate-500">The rate-based and Monte Carlo charts share a y-scale so they can be read against each other directly. What that shows is how little of the distribution a single line accounts for. The line itself is well placed &mdash; it tracks the simulated median to within a few percent (measured &minus;3.5%, &minus;1.5% and +0.4% across three households), because the engine compounds the same rate it draws around as the median of each year&rsquo;s return. The point is the distance above and below it. Read on its own, a single curve looks like an answer; against the spread of {fmtNum(MC_TRIALS)} paths it is visibly one thread of a very wide cloth.</p>
          <p className="text-slate-500">The rate-based band answers the same question far more cheaply, as a shaded band either side of the expected line that redraws as you type. Each edge takes that age&rsquo;s own quantile rate: the spread of an annualised return is &radic;(sp&sup2; + &sigma;&sup2;/T) and narrows with the horizon, so one rate cannot describe every age on a chart &mdash; held fixed it is out by 24&ndash;29% at age 50 on a 45-year plan. Re-derived per age it lands within 2&ndash;3% of the Monte Carlo.</p>
          <p className="text-slate-500">What survives is the real difference between the two. The band cannot run dry, because a smooth line has no bad decade in it; the fan can, because it is made of paths that did. So the band&rsquo;s lower edge stays optimistic, and increasingly so as a plan weakens &mdash; 5.5% out at 99.5% survival, 16.2% at 97.3%, 98% at 91.3%. Use the band to see the shape of the range as you type, and the fan when the downside is the decision.</p>
          <p className="text-slate-500">Where the lower edge touches zero, a tenth of the paths have run dry by that age. That is a statement no smooth line could have made.</p>
          <p className="text-slate-500"><strong className="text-slate-800">Sequence risk, priced.</strong> The card under the chart puts a number on the same effect rather than describing it. It takes each tier&rsquo;s 10th-percentile annualised return &mdash; the unlucky column of the Config risk matrix, over your own horizon &mdash; compounds it evenly to age {terminalAge}, and sets that against the 10th-percentile pot the simulation actually produced. The two runs share an expected return, a plan and a horizon; all that separates them is the order the returns arrive in, so the difference is sequence risk in pounds. It is one-sided by nature: the same comparison at the 90th percentile comes out far smaller, and sometimes favourable, because selling units cheaply to live on is irreversible in a way that buying them cheaply is not. While you are still contributing it disappears, and can turn mildly favourable &mdash; a bumpy path buys more units when prices are low. This is also the one thing a published return forecast cannot supply, however detailed: withdrawal order is not a property of a return distribution.</p>
        </div>
        <p className="text-xs text-slate-600 leading-relaxed"><strong className="text-slate-800">Every figure is in today&rsquo;s money, and the headline carries a &plusmn; sampling error.</strong> At {fmtNum(MC_TRIALS)} trials a difference smaller than that is noise, so treat 94.2% and 95.1% as the same answer. Check the <strong>pre-SIPP access failure</strong> line separately: a plan can survive overall while still stranding you before age {nmpa}, which is a bridging problem, not a saving-enough problem. A path counts as failed in any year that living costs or a one-off cost cannot be met from an accessible wrapper, or if the terminal pot ends below your bequest floor. Paths are seeded, so the same seed reproduces the result exactly; change the seed in Config to test a different draw of markets.</p>
        <p className="text-[11px] text-slate-500 leading-relaxed">No stage changes your plan on its own. Applying a strategy from stage 3 is a separate, deliberate click.</p>
        </PhoneCollapse>
      </div>

      <div id="doc-tournament" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><Zap className="w-4 h-4 text-indigo-600" /> Automated Strategy Tournament &amp; Optimisation Methodology</h2>
        <p className="text-xs text-slate-600 leading-relaxed">The tournament compares six ways of splitting the same annual take-home budget across the wrappers. The budget is everything the plan pays in today &mdash; pension and ISA contributions at their take-home cost, plus anything going into a general account or cash, which every strategy sweeps into its own split. Every player is run on the same {fmtNum(TOURNAMENT_TRIALS)} market paths (common random numbers), so the players are compared on identical markets rather than on separate draws. That is what makes the comparison fair; it does not make it exact. A single strategy's survival rate still moves by around half a point from one seed to the next at this path count, so read a lead smaller than about a point as sampling error. Any saved scenario can be entered as an extra player; those run exactly as saved and are not held to the same budget, which their cards state.</p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-lg space-y-1"><strong className="text-slate-800 block">1. Equal net budget</strong><p className="text-slate-500">Each strategy costs the same take-home pay. Pension money is grossed up using each owner's own salary (income tax + NIC relief, plus any employer NIC pass-through set in Config), capped by the annual allowance (£{fmtNum(P.pensionAllowance)}) and salary; ISA money is capped at £{fmtNum(P.isaAllowance)} per person; anything left over flows to a GIA.</p></div>
          <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-lg space-y-1"><strong className="text-slate-800 block">2. Conservative bridge sizing</strong><p className="text-slate-500">If spending starts before anyone can access a pension (age {nmpa}), the bridge reserve is the sum of net drawdown in those years (after guaranteed income and a working partner's take-home), uplifted by the safety margin ({E.num(plan?.config?.bridgeSafetyMargin, 30)}%) and assuming 0% real growth.</p></div>
          <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-lg space-y-1"><strong className="text-slate-800 block">3. The players</strong><p className="text-slate-500"><strong>Current plan</strong> · <strong>Survival maximiser</strong> (searches the ISA share from 0% to 100% and keeps the best survival, subject to the bridge-risk cap) · <strong>Bridge-Sized Relief</strong> (pension-first, with only the pre-access bridge carved out: the requirement is sized with growth counted on both existing balances and new contributions, then cover levels either side of it are searched, some paid in level and some over the final years only, and spare ISA capital above the reserve is moved into the pension) · <strong>Relief-First</strong> (pension first, bridge minimum kept; with a Bed &amp; SIPP transfer of spare ISA capital in full scope) · <strong>Bracket-Smoothed Sizing</strong> (pension funded only to the pot whose sustainable withdrawal plus state pension fills the basic-rate band, the rest to ISA) · <strong>Relief-First, Bridge-Last</strong> (pension-max early, ISA-max in the final years before retirement).</p></div>
          <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-lg space-y-1"><strong className="text-slate-800 block">4. Reading the results</strong><p className="text-slate-500">Rank by survival first; ties within 0.5 points are broken by the 10th-percentile pot. Watch the pre-SIPP access failure rate: a strategy can win on total survival by accepting more bridge risk. The "Partner balancing" option steers new money to the partner with the smaller projected pension so both personal allowances can be used in retirement; it costs relief if that partner pays a lower marginal rate, so it does not always win.</p></div>
        </div>
        </PhoneCollapse>
      </div>

      <div id="doc-decumulation" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><Sliders className="w-4 h-4 text-blue-600" /> Decumulation Policies &amp; Pension Drawdown Strategies</h2>
        <p className="text-xs text-slate-600 leading-relaxed">How money is withdrawn across wrappers changes lifetime tax and the size of the pot left at the end; it changes the probability of maintaining your living costs far less than the spend level, asset allocation and the pre-SIPP access bridge do.</p>
        <ul className="list-disc pl-5 text-xs text-slate-600 space-y-1.5">
          <li><strong>Tax Smoothing (default):</strong> fills the £{fmtNum(P.pa)} allowance from pension income (0%), then draws pension income up to the £{fmtNum(P.basicLimit)} higher-rate threshold (about {Math.round((1 - P.pclsProp) * P.basicRate * 100)}% effective with the {Math.round(P.pclsProp * 100)}% tax-free element), then cash, GIA and ISA, with pension income above the threshold as the last resort. Cash and ISAs are preserved as the low-volatility reserve and the tax-free shield for later life.</li>
          <li><strong>UK FIRE Bracket Fill:</strong> draws pension only up to the £{fmtNum(P.pa)} allowance, then cash, GIA and ISAs; pension income above the allowance is the last resort. Pays the least tax during your lifetime and leaves the largest pot, but that pot is mostly taxable pension. Set the pension death-tax haircut in Config to see the difference net of what beneficiaries would pay.</li>
          <li><strong>Sequential:</strong> cash → GIA → ISA → pension, no bracket management. Shown as the naive baseline; it wastes the personal allowance in early retirement.</li>
          <li><strong>Harvest unused allowance:</strong> once retired and past age {nmpa}, any unused 0% allowance is filled from the pension and the net proceeds moved to ISA (within the £{fmtNum(P.isaAllowance)} limit) or cash. It only matters when spending is largely covered by guaranteed income.</li>
          <li><strong>Phased Drawdown</strong> crystallises {Math.round(P.pclsProp * 100)}% tax-free with each withdrawal (UFPLS-style), keeping the rest invested. <strong>Full lump sum</strong> moves the maximum tax-free cash (capped at £{fmtNum(P.lsa)}) into cash savings at retirement; later withdrawals are then fully taxable.</li>
        </ul>
        </PhoneCollapse>
      </div>

      <div id="doc-guardrails" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-blue-600" /> Spending Guardrails (Guyton-Klinger)</h2>
        <p className="text-xs text-slate-600 leading-relaxed">The decumulation policy above decides <strong>where</strong> each year's money comes from. Guardrails decide <strong>how much</strong> to take, and they are a separate switch on the Config tab, off by default. With them off, every simulated year spends the plan whatever the markets did. That is the strict test, and the one every figure in this app was built on. With them on, spending reacts to the pots the way a real household's would, following the rules Jonathan Guyton and William Klinger set out in 2006, translated into this model's terms:</p>
        <ul className="list-disc pl-5 text-xs text-slate-600 space-y-1.5">
          <li><strong>The rails.</strong> The first year the pots are drawn on, the withdrawal rate is recorded: that year's draw over the combined pot. Every later year the current rate is compared to it. More than {Math.round(E.GUARDRAILS.band * 100)}% above, the draw is cut by {Math.round(E.GUARDRAILS.cut * 100)}%. More than {Math.round(E.GUARDRAILS.band * 100)}% below, it is raised by {Math.round(E.GUARDRAILS.raise * 100)}%. A 5% start has its rails at 4% and 6%.</li>
          <li><strong>The draw, not the spend.</strong> The rate is measured on what the pots are asked for after the State Pension and any other guaranteed income, because that is what a withdrawal rate means. The cut and the rise apply to that draw. A household living entirely on guaranteed income is never touched by the rule.</li>
          <li><strong>No rise after a loss.</strong> In any year the pots fell, the inflation rise that would have kept spending level is skipped and never made up. The model runs in today's money, so this appears as spending falling by the {E.num(plan?.config?.inflation, E.DEFAULT_CONFIG.inflation)}% inflation assumption in real terms.</li>
          <li><strong>No cuts at the end.</strong> The cut is switched off in the final {E.GUARDRAILS.freezeYears} years of the plan, where there is no long horizon left to protect. The rise still applies.</li>
          <li><strong>The rails follow your plan.</strong> When the plan itself changes what it asks of the pots, because the State Pension starts, a spending band begins, or an income stream ends, the rails are re-set on that new footing with every cut and rise so far carried into them. Without this the rule would read your own choices as market news: on a perfectly smooth path it raised spending to more than double by age 80, undoing a reduction the household had planned on purpose.</li>
        </ul>
        <p className="text-xs text-slate-600 leading-relaxed"><strong>What it does to the numbers, and why it is off by default.</strong> A path that survives by cutting three times still counts as a survival, so switching the rule on makes the survival rate rise for a reason the rate cannot show on its own. Two figures appear beside it to say what that cost: the spending a typical run actually lived on, and what the unlucky tenth lived on. Read the rate with those or it will flatter the plan. The safe-spend solver's answer becomes a safe <em>starting</em> spend, and it is never lower with the rule on than off, because the option to cut can only widen what a starting figure survives. The four parameters are held constant rather than exposed: the switch is one decision, and four numbers under it would turn it into a tuning exercise.</p>
        <p className="text-xs text-slate-500 leading-relaxed"><strong>Seeing where it acts.</strong> The Audit Data Table gains a column when the rule is on, naming what it did in each year of the expected path (a cut, a rise, a skipped inflation rise, or the rails being re-set) and the multiplier it has left on the draw. The expected path is smooth, so most of what it shows there is rises and re-sets; the cuts happen in the simulated bad runs, which is where the Monte Carlo figures come from. The instruction sheet from the Strategy tab includes the rule as a step, since it is a rule the household follows, not only one the simulation does.</p>
        </PhoneCollapse>
      </div>

      <div id="doc-lookahead" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-sky-600" /> Preparing for a One-off Cost</h2>
        <p className="text-xs text-slate-600 leading-relaxed">A one-off cost you enter on Plan Inputs is a cost the plan can see coming, but until this setting it was met as if it were a surprise: read in its own year and paid by the cost order, cash then GIA then ISA and finally the pension, with no ceiling on the pension draw. A cost larger than the liquid wrappers therefore landed on the pension in one year and went through the higher and additional bands, when the same money drawn over the years before would have come out at the basic rate. The setting is <strong>Prepare for one-off costs, years ahead</strong> on the Config tab; the default is {E.DEFAULT_CONFIG.lookaheadYears === 0 ? 'off (0)' : `${E.DEFAULT_CONFIG.lookaheadYears} years`}.</p>
        <ul className="list-disc pl-5 text-xs text-slate-600 space-y-1.5">
          <li><strong>What it does.</strong> From that many years ahead, each year the plan sets the liquid wrappers, grown at the rate they earn, against every known cost inside the window. Whatever would still be short is divided by the years left until the cost lands, and that share is drawn from the pension on top of the living draw, never past the basic-rate limit ({formatGBP(P.higherRateStartsAt)} of total taxable income). The proceeds go to the ISA up to the allowance and then to cash, not the GIA, because money for spending within a few years should not realise a gain on the way out.</li>
          <li><strong>Where it cannot act.</strong> Only once retired and past the pension access age, since before that the pension cannot be drawn. A household whose living draw already reaches the basic-rate limit has no room under the ceiling, and the rule correctly does nothing rather than draw at 40%. A cost the liquid wrappers will cover on their own leaves it idle too.</li>
          <li><strong>Self-correcting, not scheduled.</strong> It is recomputed from the balances every year: a rise in the markets shrinks the shortfall and the reserve stops growing, a fall widens it and the next year draws more. Nothing is earmarked, because the cost order spends the liquid wrappers first when the year comes.</li>
          <li><strong>What it costs.</strong> Money leaves the pension's tax-free growth a few years early and part of it sits in cash meanwhile. That is the trade against twenty or more points of tax on the year the cost lands.</li>
        </ul>
        <p className="text-xs text-slate-500 leading-relaxed"><strong>What the study found.</strong> Over the scenario library with a cost of a quarter or a half of the household's wealth placed six years into retirement, the rule was idle for most households, whose liquid wrappers covered the cost anyway. Where it acted, the cost-year pension draw fell by a hundred thousand pounds or more, lifetime tax fell by twenty to seventy thousand, the median terminal pot rose rather than fell, and survival rose by up to three points with no household worse by more than a point. The Audit Data Table gains a <strong>Set aside</strong> column when the setting is on, showing the years it acted and the cost year each draw was for; the instruction sheet on the Strategy tab includes it as a step.</p>
        </PhoneCollapse>
      </div>

      <div id="doc-coverage" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-indigo-600" /> Modelling Decisions, Coverage &amp; Known Gaps</h2>
        <p className="text-xs text-slate-600 leading-relaxed">Where the rules leave room for judgement, this is the decision the model makes and why. Read this before trusting a number.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Decisions taken</h3>
        <ul className="list-disc pl-5 text-xs text-slate-600 space-y-1">
          <li><strong>Everything is in today's money.</strong> Growth uses each tier's <em>real</em> rate, so every pot, spend and bequest figure is in today's purchasing power. The "Combined (Nominal)" chart series is the only place inflation is added back, for display. A £100,000 bequest floor therefore means £100,000 of today's money. Do not gross it up.</li>
          <li><strong>Pay is flat in real terms unless you say otherwise.</strong> Salary, or trading profit for the self-employed, is held at the figure you enter for every working year. Because the projection is in today's money that is not a frozen wage, it is pay rising exactly with inflation. Set a real growth rate per person under Advanced inputs to model promotions or a career winding down; it compounds on top of inflation and feeds the relevant-earnings cap, the annual allowance taper and the relief rate on every pension contribution.</li>
          <li><strong>The MPAA is derived, not declared.</strong> The model runs the expected path once, finds the first year each person draws taxable pension income, and applies the £{fmtNum(P.mpaaLimit)} allowance from that age. It assumes you have <em>not</em> already flexibly accessed a pension: reasonable for planning, wrong if you have, which would need the trigger set earlier.</li>
          <li><strong>Carry-forward is not consumed.</strong> Unused allowance from the prior three years is offered as headroom but is not tracked as being used up, so a plan that leans on it repeatedly is optimistic. It never lifts the earnings limit, and it accrues at each prior year's <em>tapered</em> allowance.</li>
          <li><strong>The annual allowance taper keys off earnings.</strong> HMRC tapers on adjusted income, which adds employer contributions; the model only knows earnings, so the taper is approximate for anyone near the £{fmtNum(P.aaTaperThr)} threshold.</li>
          <li><strong>A blank salary means "unknown", not "zero".</strong> While you are still working, leaving salary empty leaves the pension allowance unconstrained rather than dropping it to £{fmtNum(P.pensionNoEarningsLimit)}. Enter a salary for an accurate limit.</li>
          <li><strong>CGT is realisation-based.</strong> Gains are booked only when the GIA is actually sold, using a running cost basis. Gains are wiped by the uplift on death, so nothing is charged on whatever remains at the terminal age.</li>
          <li><strong>The tournament holds contributions equal.</strong> Every strategy is re-priced to cost the same total over the accumulation years as your current plan, by solving its contribution escalation. Without this a strategy could win simply by asking you to pay in more.</li>
          <li><strong>Allowance harvesting is a bequest tool.</strong> It never improves survival. It moves money from a pot taxed on death into one that is not. It is worth nothing unless you set a pension death tax rate, and close calls are broken on the pot left <em>after</em> that tax.</li>
          <li><strong>The self-employed get income tax relief only.</strong> A sole trader cannot salary sacrifice, so a personal contribution saves income tax at the marginal rate but no NIC, and no employer NIC can be passed through. That is 40% relief for a higher-rate trader against 42% for an employee, and 20% against 28% in the basic band. Set the employment type per person in Advanced inputs.</li>
          <li><strong>Allowances are frozen in real terms</strong> at the Config figures. Any future rise in the ISA or pension allowance is not modelled, so long staging schedules are deliberately cautious.</li>
        </ul>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Modelled</h3>
        <p className="text-xs text-slate-600 leading-relaxed">Income tax including the personal-allowance taper, employee Class 1 NIC and self-employed Class 4 NIC, the {Math.round(P.pclsProp * 100)}% tax-free element capped at the £{fmtNum(P.lsa)} Lump Sum Allowance, the £{fmtNum(P.pensionAllowance)} annual allowance with taper and three-year carry-forward, the relevant-earnings limit, the MPAA, ISA allowances, realisation-based CGT with its annual exempt amount and band split, state pension timing, the pre-SIPP access bridge, one-off deposits with multi-year staging, one-off costs, spending bands by age, salary-sacrifice relief including any employer NIC pass-through, and relief at source for the self-employed.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Not modelled yet</h3>
        <ul className="list-disc pl-5 text-xs text-slate-600 space-y-1">
          <li><strong>Lumpy self-employed profits.</strong> Trading profit is carried as a single figure that grows at a steady rate, exactly like a salary. Real self-employment swings year to year, and a bad year can waste an annual allowance that carry-forward only partly recovers. <strong>Class 2 NIC</strong> is also not charged: it stopped being mandatory above the Small Profits Threshold in 2024, and the voluntary route for those below it does not change a projection. Payments on account, the trading allowance, capital allowances and incorporation are all out of scope.</li>
          <li><strong>Devolved income tax:</strong> covered. Set where you pay tax in Config. Scotland uses its own six bands, Wales
            is offered but currently matches England and Northern Ireland. Only the bands are devolved: National Insurance, capital gains
            tax, the personal allowance and its taper apply unchanged, and relief at source on a pension contribution stays at 20%.
            Note that the region only shows up where the model actually routes income through the tax calculation - pension drawdown,
            the state pension and other taxable income - so it does not change a projection whose earning years are all before anyone
            has retired.</li>
          <li><strong>Inheritance tax on the estate.</strong> The pension death tax setting applies a haircut to leftover pension only, so it represents the <em>extra</em> tax a pension suffers relative to an ISA, not IHT on everything.</li>
          <li><strong>Defined benefit pensions</strong> beyond entering them as a taxable income stream; no accrual, revaluation or transfer values.</li>
          <li><strong>Tax on cash interest.</strong> The Cash Savings wrapper earns its tier&rsquo;s return and nothing is charged on it, so it stands for a <strong>cash ISA</strong>, or for savings inside your personal savings allowance. There is no wrapper for taxable cash above that allowance: the nearest proxy is Other Investments at a low risk tier, which taxes the growth as CGT on disposal rather than as interest every year &mdash; later, at a lower rate and after a larger allowance, so it flatters a large cash holding. Measured on a &pound;100,000 holding at the Low Risk tier, the interest tax not charged runs to about &pound;2,600 a year for a basic-rate payer and &pound;5,400 for a higher-rate one.</li>
          <li><strong>Care costs, the Lifetime ISA, the National Minimum Wage floor on salary sacrifice, dividend and savings-interest taxation inside the GIA, share pooling and the 30-day CGT rule.</strong></li>
          <li><strong>Allowance and threshold changes</strong> announced for future years, and any change to the state pension triple lock.</li>
        </ul>
        <p className="text-xs text-slate-500 leading-relaxed">This is an educational model, not advice. Where a figure matters to a real decision, check it against current HMRC guidance or a regulated adviser.</p>
        </PhoneCollapse>
      </div>

      <div id="doc-taper" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><HelpCircle className="w-4 h-4 text-blue-600" /> Spending by Age</h2>
        <p className="text-xs text-slate-600 leading-relaxed">Retirement spending often isn't flat. Set what a stretch of years actually costs in Plan Inputs as bands: a start age, an end age and what those years cost in today's money. A band that names ages 58 to 67 at {formatGBP(45000)}, then 68 to 79 at {formatGBP(34000)}, then 80 onwards at {formatGBP(40000)}, says exactly that, including the rise at the end for care. Ages are "Myself" ages.</p>
        <p className="text-xs text-slate-600 leading-relaxed">Bands only override the years they cover. Any year outside every band falls back to the headline living spend, so naming a single expensive stretch is enough; you do not have to describe the whole retirement. Leave the end age blank to run a band to the terminal age. If two bands overlap the earlier one wins for the shared years, and the model says so in the warnings rather than picking silently.</p>
        <p className="text-xs text-slate-500 leading-relaxed">Bands replaced an older pair of percentage "tapers" that could only step spending down at two fixed ages. Any saved plan still carrying tapers is converted to the equivalent bands when it loads, so its projection is unchanged. The safe-spend solver scales the whole shape at once: it finds the multiple of your headline spend that survives, and every band moves with it in proportion.</p>
        </PhoneCollapse>
      </div>

      <div id="doc-risk-profiles" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-blue-600" /> Asset Allocations, Return Bounds &amp; Volatility (σ)</h2>
        <p className="text-xs text-slate-600 leading-relaxed">Each wrapper is assigned a risk tier carrying an expected real return (treated as the median annual rate), a volatility, and a forecast uncertainty. The first two describe the <em>path</em>; the third describes how sure we are of the average that path is scattered around, and the distinction matters more the longer you plan for. Volatility averages out as σ/√T. Being wrong about the long-run average does not average out at all, so it is drawn once per simulated path and then lived with, giving an annualised spread of √(u² + σ²/T). The built-in tiers set that uncertainty to zero, which is itself a claim — that we know the long-run average and are only unsure of the route — and a published set of capital market assumptions will generally say otherwise.</p>
        <p className="text-xs text-slate-600 leading-relaxed"><strong className="text-slate-800">&ldquo;Expected&rdquo; here means the middle, not the average.</strong> The figure in the first column is the <em>median</em> rate: half the simulated years land above it and half below. Compound the middle rate and you get the middle outcome, which is why the Expected line on the Projection chart sits almost exactly on the simulation&rsquo;s median &mdash; within half a percent on a plain lump sum, and within about 3&frac12;% on a real plan, where contributions and tax blur it slightly.</p>
        <p className="text-xs text-slate-600 leading-relaxed">The <em>average</em> would be a much bigger number and a far less useful one. Picture a casino floor: nobody is made to stop while they are winning, but everybody stops at zero. Money behaves the same way. A pot that compounds well keeps compounding with nothing above it, while a pot that runs dry is finished and stays finished &mdash; so a handful of runaway futures drag the average up and away from anything the rest experience. On one ordinary plan modelled here the middle outcome is {formatGBP(7193811)} while the average is {formatGBP(22457043)}: more than three times higher, and a figure almost nobody in the simulation actually ends up with. You plan around the outcome in the middle, so the middle rate is what this model compounds. It is the standard convention too &mdash; published capital market assumptions quote annualised returns, not arithmetic ones.</p>
        <p className="text-xs text-slate-600 leading-relaxed">The 10th and 90th percentile columns beside them are that spread at the two tails: over your horizon the annualised return lands between them eight times in ten. They also draw the rate-based band on the Projection chart, re-derived at every age rather than held at one rate, because that spread narrows as the horizon lengthens and a single rate is wrong everywhere except the horizon it came from. What they cannot do is stand in for the simulation: a smooth curve contains no bad decade and cannot run dry, so its lower edge stays optimistic on a plan under strain. All wrappers move together (one market factor scaled by each tier's σ), so the correlations a published set also carries cannot be used without a second factor; the historical backtest blends real US equity and bond returns by the tier's equity weight ({Object.entries(E.RISK_EQUITY_WEIGHTS).map(([k, v]) => `${k.replace(' Risk', '')} ${Math.round(v * 100)}%`).join(', ')}).</p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          {Object.entries(activeRiskMatrix).map(([k, v]) => (
            <div key={k} className="p-3 bg-slate-50 border border-slate-200 rounded-lg space-y-1"><span className="font-bold text-slate-800">{k} ({v.label})</span><p className="text-slate-500">Expected real {E.num(v.real, 0).toFixed(2)}% pa, σ = {E.num(v.volatility, 0).toFixed(1)}%.</p></div>
          ))}
        </div>
        </PhoneCollapse>
      </div>

      <div id="doc-one-off-deposits" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><Plus className="w-4 h-4 text-blue-600" /> One-Off Deposits &amp; Multi-Year Staging</h2>
        <p className="text-xs text-slate-600 leading-relaxed">A one-off deposit is a lump sum paid into a chosen wrapper in a chosen year. Because ISAs and pensions are capped each tax year, the engine checks the deposit against that year's remaining allowance before it lands.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Where the money comes from</h3>
        <p className="text-xs text-slate-600 leading-relaxed"><strong>External (new capital)</strong> is money arriving from outside the plan (an inheritance, a bonus, a property sale), and nothing is deducted from your existing pots. Choosing any wrapper instead treats it as an internal transfer: the full amount is taken out of that pot in the deposit year. If that pot does not hold enough at the time, the engine moves what is there and the rest is recorded as a shortfall.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">How much fits this year (headroom)</h3>
        <ul className="list-disc pl-5 text-xs text-slate-600 space-y-1">
          <li><strong>S&amp;S ISA:</strong> {formatGBP(P.isaAllowance)} less whatever your regular ISA contribution is that year.</li>
          <li><strong>Carry forward:</strong> unused annual allowance from the previous three tax years is added to the current year's. Years inside the projection are worked out from your contribution schedule; for the three years before it starts the model has no data, so it assumes nothing unless you enter a figure under Advanced inputs. Carry forward never lifts the earnings limit, so it does nothing for someone with no relevant earnings.</li>
          <li><strong>Pension after flexible access:</strong> taking taxable pension income permanently replaces the allowance with the money purchase annual allowance of {formatGBP(P.mpaaLimit)}, and carry forward is no longer available. Taking only tax-free cash, or buying an annuity, does not trigger it. You do not enter this: the model works out the first year your plan draws taxable pension income and applies it from there.</li>
          <li><strong>Pension:</strong> {formatGBP(P.pensionAllowance)}, but capped at your <em>relevant UK earnings</em>, less your regular pension contribution that year. Only employment and self-employment income counts as earnings; DB pensions, annuities, rent, dividends and interest do not. With no relevant earnings the limit is <strong>{formatGBP(P.pensionNoEarningsLimit)}</strong>, which is what normally applies once you have retired. If you leave your salary blank while still working, the engine treats your earnings as unknown and does not constrain the allowance.</li>
          <li><strong>Other Investments and Cash Savings:</strong> no annual limit, so a deposit there is never staged.</li>
        </ul>
        <p className="text-xs text-slate-600 leading-relaxed">Headroom is therefore not a fixed number. It shrinks in later years if your regular contributions escalate, and it changes again at retirement, when regular contributions stop and the pension earnings test begins to constrain it. The card above the deposits table shows this tax year only. Each deposit row shows the headroom for its own year.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">If the deposit exceeds the headroom</h3>
        <p className="text-xs text-slate-600 leading-relaxed">Rather than silently breaching the allowance, the deposit is staged across several tax years:</p>
        <ol className="list-decimal pl-5 text-xs text-slate-600 space-y-1">
          <li>As much as fits the current year's allowance goes straight into the target wrapper.</li>
          <li>The surplus is parked in <strong>Other Investments (GIA)</strong>, where it stays invested and grows at that account's risk tier. Once it has grown, moving it out is a disposal, so with CGT switched on each transfer year realises a proportional gain.</li>
          <li>At the start of each following tax year, as much as that year's allowance permits is moved from the GIA into the target wrapper, repeating until nothing is left. You can redirect where the staged money ends up from the row's settings icon.</li>
        </ol>
        <p className="text-xs text-slate-600 leading-relaxed">Where several deposits compete for the same person's allowance in the same year, they are resolved in date order, so one allowance is never counted twice. If a market fall shrinks the parked money, that year's transfer is capped at whatever the GIA actually holds. Anything still parked at the end of the plan stays in Other Investments and is flagged as a warning.</p>

        <p className="text-xs text-slate-500 leading-relaxed"><strong>Assumption:</strong> allowances are held fixed in real terms at the figures in Config ({formatGBP(P.isaAllowance)} ISA, {formatGBP(P.pensionAllowance)} pension, {formatGBP(P.pensionNoEarningsLimit)} with no earnings). Any future increase in these limits is <strong>not</strong> modelled, so a long staging schedule is a cautious estimate. If allowances do rise, the money would move across in fewer years than shown. You can edit the figures in Config to test a different assumption.</p>
        </PhoneCollapse>
      </div>

      {/* Held back with the tab itself - this section documents a tab the beta does not show,
          and half of it names controls the reader cannot reach. Restored by the same flag. */}
      {SHOW_INHERITANCE && (
      <div id="doc-inheritance" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><Gift className="w-4 h-4 text-purple-600" /> Inheritance Tax: the rules, and what is not modelled</h2>
        <p className="text-xs text-slate-600 leading-relaxed">Rules as published for 2026/27 and checked in September 2026. Three of the four regimes below changed between 2025 and 2027, so they are all editable in Config rather than baked in — if a Budget moves them, change the figure rather than waiting for the app.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">The one change that inverts the usual advice</h3>
        <p className="text-xs text-slate-600 leading-relaxed">From <strong>6 April 2027</strong> an unused pension counts as part of your estate. Before that date it sat outside, which is the entire basis of the conventional &ldquo;spend everything else first&rdquo; advice. And if you die at <strong>{E.num(plan?.config?.pensionIncomeTaxFromAge, 75)} or over</strong>, your beneficiaries then pay their own income tax on what they draw from it — on top of the inheritance tax the estate already paid. At the additional rate that is roughly <strong>67%</strong> of that pound gone, against 40% for the same pound in an ISA.</p>
        <p className="text-xs text-slate-600 leading-relaxed">We tested whether that means you should drain the pension early. <strong>It does not.</strong> Across 420 households ranked on what heirs actually receive, a &ldquo;pension first&rdquo; policy won 21 times out of 5,040 — and on one wealthy household it left £9.8m where the best policy left £22.0m. Emptying a pension early means paying income tax at <em>your</em> marginal rate, on a large pot, during retirement, and the proceeds cannot be sheltered fast enough because the ISA allowance is £20,000 a year. The double charge is real and still cheaper than volunteering for the single one early.</p>
        <p className="text-xs text-slate-600 leading-relaxed">What the change really does is make the answer depend on facts a projection never asked for. The best policy for a household dying at 74 wins 59% of the time; for the same household dying at 80 it wins 21%. That is why this tab prices several ages rather than asking you to pick one.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">The allowances</h3>
        <div tabIndex={0} className="overflow-x-auto">
          <table className="w-full text-left text-[11px] border-collapse">
            <tbody className="divide-y divide-slate-100">
              <tr><td className="py-1.5 pr-3 font-semibold text-slate-700">Nil-rate band</td><td className="py-1.5 pr-3 font-mono">{formatGBP(E.num(plan?.config?.ihtNrb, 325000))}</td><td className="py-1.5 text-slate-600">Frozen to 5 April 2031.</td></tr>
              <tr><td className="py-1.5 pr-3 font-semibold text-slate-700">Residence nil-rate band</td><td className="py-1.5 pr-3 font-mono">{formatGBP(E.num(plan?.config?.ihtRnrb, 175000))}</td><td className="py-1.5 text-slate-600">Only if a home passes to a child, grandchild or step-child. Capped at the home&rsquo;s own value, and lost £1 for every £2 of estate above {formatGBP(E.num(plan?.config?.ihtRnrbTaperFrom, 2000000))}.</td></tr>
              <tr><td className="py-1.5 pr-3 font-semibold text-slate-700">Transferred from a late spouse</td><td className="py-1.5 pr-3 font-mono">up to {formatGBP(E.num(plan?.config?.ihtNrb, 325000) + E.num(plan?.config?.ihtRnrb, 175000))}</td><td className="py-1.5 text-slate-600">Usually 100% of both, because anything passing to a spouse is exempt and so uses neither. Commonly missed.</td></tr>
              <tr><td className="py-1.5 pr-3 font-semibold text-slate-700">Rate</td><td className="py-1.5 pr-3 font-mono">{E.num(plan?.config?.ihtRate, 40)}%</td><td className="py-1.5 text-slate-600">Falling to {E.num(plan?.config?.ihtCharityRate, 36)}% where at least {E.num(plan?.config?.ihtCharityThresholdPct, 10)}% of the estate goes to charity — so just past that point, giving more away costs your family nothing.</td></tr>
              <tr><td className="py-1.5 pr-3 font-semibold text-slate-700">Quick succession relief</td><td className="py-1.5 pr-3 font-mono">{(E.DEFAULT_CONFIG.qsrScale || []).join('/')}%</td><td className="py-1.5 text-slate-600">Where you inherited within five years and tax was paid then, by whole years elapsed. <strong>Not automatic</strong> — it must be claimed.</td></tr>
              <tr><td className="py-1.5 pr-3 font-semibold text-slate-700">Death on active service</td><td className="py-1.5 pr-3 font-mono">exempt</td><td className="py-1.5 text-slate-600">Full exemption for armed forces deaths from service, and since 2014 emergency services personnel and anyone targeted because of their job.</td></tr>
            </tbody>
          </table>
        </div>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Who inherits changes the tax, not just the shares</h3>
        <p className="text-xs text-slate-600 leading-relaxed">A spouse or civil partner is fully exempt and passes their unused allowances on. A charity is exempt and can pull the rate down for everyone else. A direct descendant unlocks the residence allowance. Anyone else gets no relief. And because an inherited pension is taxed at the <em>recipient&rsquo;s</em> marginal rate, the same pot is worth materially more to a grandchild with no income than to a child earning six figures — identical estate, identical will, different outcome.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Two documents, not one</h3>
        <p className="text-xs text-slate-600 leading-relaxed">Your will divides the house, ISAs, investments and cash. Your pension does not pass under it at all — it goes to whoever is named on the <strong>nomination form</strong> held by your scheme, which most people completed once on joining. The tab asks for both because an inherited pension is taxed at the <em>recipient&rsquo;s</em> marginal rate: nominating it to someone with an unused personal allowance, and leaving the taxed assets to higher-rate earners, is usually the single most valuable choice available. How long each person draws it over matters just as much — every year of drawing gets its own allowance and basic-rate band, so a young grandchild spreading it over twenty years pays a fraction of what the same pot costs drawn over five.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Selling your home does not lose the residence band</h3>
        <p className="text-xs text-slate-600 leading-relaxed">If you sell or give away the home on or after 8 July 2015 — to pay for care, typically — the <strong>downsizing addition</strong> preserves the band it would have given, as long as assets of at least that value pass to direct descendants instead. The plan applies it whenever the home is marked as sold. A partial downsizing, where you move somewhere cheaper, would need the value of both properties and is not asked for, so a household that trades down is modelled on the more cautious footing of having kept the newer home only.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Gifts out of income</h3>
        <p className="text-xs text-slate-600 leading-relaxed">The exemption for <em>normal expenditure out of income</em> (s.21) is immediate, unlimited and needs no seven years: a habitual gift, paid from income rather than capital, that leaves your standard of living intact. This is the only gift that helps someone who does not expect to live seven years, and it is claimed by the executors on form IHT403 — which is far easier when the giver kept a record. The plan checks the arithmetic half of the test, comparing the gift against guaranteed income and earnings less living costs, in the <em>leanest</em> year rather than on average. It excludes pension drawdown from that income figure even though HMRC will often accept regular pension income, because a gift that fails the test becomes an ordinary transfer with a seven-year clock. Whether the gift is genuinely habitual is a question about a pattern of behaviour that no calculator can settle.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">The estate optimiser, and what it will not do</h3>
        <p className="text-xs text-slate-600 leading-relaxed">The Inheritance tab carries a second search, for households the contributions tournament cannot help because nothing is being paid in. It ranks six choices on one number &mdash; what the heirs keep, counting both the estate and anything handed over in the meantime, after inheritance tax and after their own income tax on drawing an inherited pension down: the <strong>order you draw wrappers down</strong>, <strong>how far up the tax bands you draw the pension each year</strong>, a <strong>gift now</strong>, <strong>how the pension is split between the people inheriting it</strong>, <strong>moving money between wrappers up to the allowances</strong> (including the £3,600 a year that basic-rate relief buys for £2,880 even with no earnings at all), and <strong>giving exempt compensation away before its window closes</strong>. Each lever is also measured on its own, against your plan untouched, because crediting whichever was searched first with everything the others deliver would send you after the wrong one.</p>
        <p className="text-xs text-slate-600 leading-relaxed">Two of those deserve a note. <strong>Drawing the pension past the tax-free allowance</strong> costs 20% today and only pays off if you die at 75 or over, when the pension is taxed twice &mdash; by the estate, then by the heir. The sign flips on the death age, so it is searched rather than recommended. And the <strong>pension split</strong> is swept in 5% steps rather than handed to whoever earns least, because that rule of thumb breaks on a large pot: £1.5m drawn over five years reaches the additional rate whoever receives it, while splitting it uses two sets of allowances. On one household here, half to a four-year-old and half to a £150,000 earner beat all of it to the four-year-old by £18,842.</p>
        <p className="text-xs text-slate-600 leading-relaxed">One thing the search will tell you it cannot improve: <strong>who receives which asset under your will</strong>. Inheritance tax is charged on the estate before it is divided, so among beneficiaries who are all taxable, giving one the house and another the ISA changes who gets what and not what survives. It moves the total only when someone exempt is named &mdash; a spouse or a charity &mdash; and then it is a question about who you want to benefit rather than about tax.</p>
        <p className="text-xs text-slate-600 leading-relaxed">Two things it deliberately refuses. It will not search <strong>how long your heirs take the pension</strong>, because that is their decision made after your death, and a candidate that won by assuming twenty years of patience from someone else would not be a plan &mdash; it is reported as a sensitivity instead. And it will not rank a <strong>charitable gift</strong>: leaving 10% cuts the rate from 40% to 36% but always leaves the family with less, so ranking it on what the heirs keep would score a donation as a failure. The cost and the benefit are both shown, and the choice stays yours. Nor will it recommend anything that leaves you short: a variant that breaks a plan which otherwise survives is rejected rather than ranked, however well it does for the estate.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Compensation, and the credit it carries</h3>
        <p className="text-xs text-slate-600 leading-relaxed">Payments under the <strong>infected blood scheme</strong> administered by IBCA are exempt from income tax and capital gains tax, and for inheritance tax they carry a <strong>credit</strong> rather than an exemption: under para 5 of Sch 15 Finance Act 2020, where a qualifying payment <em>is at any time received</em>, the tax on the death is reduced by {E.num(plan?.config?.ihtRate, 40)}% of the payment, capped at the tax that would otherwise be due. Post Office Horizon, Windrush, Grenfell, the Troubles Permanent Disablement scheme and vaccine damage payments run through the same machinery.</p>
        <p className="text-xs text-slate-600 leading-relaxed">Three consequences the plan models, and each one moves the answer: <strong>what happened to the money is irrelevant</strong> &mdash; there is no tracing test, so an award spent, invested, paid into a pension or used to clear a mortgage earns the credit in full; <strong>the estate is unchanged</strong>, so the {formatGBP(E.num(plan?.config?.ihtRnrbTaperFrom, 2000000))} residence-band taper and the 10% charity test are measured before the credit and not after it; and it <strong>cannot create a refund</strong>, being capped at the bill alongside quick succession relief. Enter the payment received, not what is left of it.</p>
        <p className="text-xs text-slate-600 leading-relaxed">Giving the money away is a separate relief with its own deadline: <strong>two years from the day you were paid</strong>, or two years from 4 December 2025 for anyone already holding an award when the relief was announced, whichever is later. Enter the date and the tab works out the deadline. <strong>You do not have to tell it which gifts came from the award.</strong> It knows the amount, the date and so the window, so a gift dated inside it is presumed to have come from the award while any of it remains &mdash; earliest first, split where a gift is larger than what is left, and left alone where the gift has already survived seven years and needs no relief. There is deliberately no way to say a gift did <em>not</em> come from the award. Money carries no label: a household holding an award alongside other savings and giving some away inside the window can always say the gift was the award, so an opt-out could only ever be wrong in the direction that costs money &mdash; and on one real plan it sat set, unnoticed, at a cost of £122,000. A saved plan carrying the old flag has it dropped on load. A gift dated after the window is priced as the ordinary transfer it has become, and the tab says so.</p>
        <p className="text-xs text-slate-600 leading-relaxed"><strong>One reading worth knowing about, because it is a reading and not a quotation.</strong> The credit and the window are treated as independent: giving the award away does not forfeit the credit. The cautious alternative &mdash; netting the gifts off the credit, so the same money cannot be relieved twice &mdash; was tried first and measured, and it makes the window worth about £1,200. A relief created at the 2025 Budget precisely because secondary transfers were being taxed cannot have been designed to be worth £1,200, and the statute relieves tax on a death where a payment &ldquo;is at any time received&rdquo; without netting anything. So both apply, to two different events: the credit on the death, the window on the gift. It is the more generous of the two readings, and the one to revisit if HMRC&rsquo;s guidance disagrees.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Business Relief: priced if you own it, never suggested</h3>
        <p className="text-xs text-slate-600 leading-relaxed">Two different questions live behind one relief, and this tab now answers one of them. <strong>Valuing what you already own</strong> is modelled: add a business, farmland or unquoted shares under <em>anything else you own</em> and the estate is priced with the relief. From 6 April 2026 that is 100% up to a {formatGBP(E.num(plan?.config?.brAprAllowance, 2500000))} allowance shared between business and agricultural property, {E.num(plan?.config?.brAprReducedRatePct, 50)}% above it, and {E.num(plan?.config?.aimReliefRatePct, 50)}% flat on shares not listed on a recognised exchange, which do not touch that allowance. That allowance is <strong>transferable between spouses</strong>, on the same percentage basis as the nil-rate band, so there is a box for it under <em>widowed</em> once you have entered relievable property. A death before that date still gets the old unlimited 100%, and the tab switches on the death year you choose. Relief needs the asset <strong>owned for two years</strong> at death, so the tab asks when you acquired it and gives nothing where the test fails.</p>
        <p className="text-xs text-slate-600 leading-relaxed"><strong>Whether to buy into them</strong> is not modelled, and is deliberately absent from the optimiser. That same two-year test makes it the wrong tool for anyone with a short prognosis — the household this tab is most used by — and the assets that qualify carry investment risk far above anything else in the plan, so a tool that priced the tax saving without pricing that risk would be recommending a trade on half the picture. Two simplifications inside what is modelled: relief is scaled by the share of your will going to people who actually pay tax, because relief on a legacy to a spouse is wasted, but a will leaving the business to one child and the house to another is beyond a single set of percentages; and only the agricultural value of farmland qualifies, where development value above it does not, so enter the agricultural figure. The {formatGBP(E.num(plan?.config?.ihtRnrbTaperFrom, 2000000))} residence-band taper is measured before reliefs (s.8D(5)), so a fully relieved farm still pushes the residence allowance away — the tab does that too.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">What this does not model</h3>
        <p className="text-xs text-slate-600 leading-relaxed">Everyone receives the same proportion of every wrapper: a will leaving the pension to one person and the ISA to another is a legal document, not a plan input. An inherited pension is assumed drawn evenly over {E.num(plan?.config?.inheritedPensionSpreadYears, 5)} years at the income each beneficiary has given, which holds only while their circumstances do. Gifts, the seven-year rule, taper relief and regular gifts out of income are modelled; carrying an unused annual exemption forward is not, nor are the small-gift and wedding exemptions, a deed of variation after death, or life cover written in trust. Assets outside your wrappers are held flat in real terms and are never sold to fund your spending, so a business or second home you would in fact live off is understated as income and overstated as estate. Neither are trusts, business succession, or domicile.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Why only one gift is ever suggested</h3>
        <p className="text-xs text-slate-600 leading-relaxed">Above {formatGBP(E.num(plan?.config?.ihtRnrbTaperFrom, 2000000))} the residence allowance is withdrawn £1 for every £2, and the test for it looks at what you <strong>owned at death</strong>. Money given away is not owned at death — so that allowance comes back the day the gift is made, seven years or not. Nothing else about gifting is so clear-cut: inside seven years a gift consumes the {formatGBP(E.num(plan?.config?.ihtNrb, 325000))} allowance the estate would have used anyway, so it is close to tax-neutral, and presenting it as a saving would be misleading. The tab therefore suggests the one gift that clears the taper and says plainly which part of the saving is certain and which part still needs the seven years.</p>
        <p className="text-xs text-slate-600 leading-relaxed">Sizing that gift is done by running your own plan, not by subtracting the excess: money given away also stops growing, and spending that would have come from it comes out of a pension instead, taxed on the way — so each £1 given can take £1 to £2 off the estate, and suggesting the excess itself would suggest roughly twice what is needed. The search stops at the largest gift the plan can still afford, since an allowance is no use to someone who has run out of money.</p>
        <p className="text-xs text-slate-600 leading-relaxed"><strong>Giving away your home and continuing to live in it does not remove it from your estate.</strong> That is a gift with reservation of benefit, it is the most common estate-planning mistake there is, and no figure on this page will warn you about it.</p>
        <p className="text-xs text-slate-500 leading-relaxed">All of this is illustration, not advice. Inheritance tax turns on facts about your family and your assets that a planning tool has no way to hold, and the amounts involved are usually large enough to be worth an hour of a professional&rsquo;s time.</p>
        </PhoneCollapse>
      </div>
      )}

      <div id="doc-priorities" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><Trophy className="w-4 h-4 text-blue-600" /> The Recommended Policy, and the Trade-offs Around It</h2>
        <p className="text-xs text-slate-600 leading-relaxed">A decumulation policy is only &quot;best&quot; relative to what you are trying to achieve. Across 420 test households, ranking on the size of the eventual pot rather than on avoiding depletion changed the recommended policy for <strong>75% of them</strong> &mdash; and took the simplest policy, Sequential, from winning 1% of households to winning 46%. Nothing about the policies changed; only the question being asked of them.</p>
        <p className="text-xs text-slate-600 leading-relaxed">Asking you to rank six abstract priorities before you have seen a single figure is the wrong way round. So the policy search runs every combination first &mdash; five policies, two ways of taking the tax-free cash, and whether the personal allowance is harvested, eighteen in all &mdash; on the same market paths, and then does two things with the results.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">First, it recommends</h3>
        <p className="text-xs text-slate-600 leading-relaxed">The recommendation is the combination with the best chance of staying solvent to your final age. Where several are within <strong>{E.RATE_EPSILON_PTS} percentage point</strong> of each other on survival &mdash; close enough that the simulation cannot honestly separate them &mdash; the near-tie is settled by resilience in poor markets, then by what is left behind, and so on down the default order. Running out of money is the one outcome no later good luck can undo, and it is not symmetric with the others: a smaller bequest is a disappointment, an empty pot at 84 is a crisis. That is why survival goes first and is never traded away by the recommendation itself.</p>
        <p className="text-xs text-slate-600 leading-relaxed">The search runs twice, on two independent sets of market paths, and ranks on the two runs combined. Where the two runs would each have recommended a different combination, the page says so: that is a close call the simulation cannot settle at this budget, and the other run&apos;s pick is offered alongside the recommendation rather than discarded. Either is a sound choice; the numbers are simply too close to separate them.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Then, it prices the alternatives</h3>
        <p className="text-xs text-slate-600 leading-relaxed">For each of the other five priorities it finds the combination that is best on that measure and states, in your own numbers, what switching to it would gain and what it would cost: <em>&pound;85,000 more in the typical pot, for 1.8 points of survival</em>. Three rules keep those cards honest:</p>
        <ul className="text-xs text-slate-600 leading-relaxed list-disc pl-5 space-y-1">
          <li><strong>A card appears only where there is a real difference.</strong> The gain has to exceed that measure&apos;s own tie threshold &mdash; {E.RATE_EPSILON_PTS} point on a rate, {Math.round(E.MONEY_EPSILON_REL * 100)}% on an amount of money, or the thresholds you set under Advanced. A difference the ranking itself would call a tie is not a choice, it is simulation noise with a button on it. If nothing clears the bar, the page says so rather than inventing a decision for you.</li>
          <li><strong>Nothing more than {E.MAX_SURVIVAL_SACRIFICE_PTS} points below the best survival is ever offered.</strong> The same safety limit that bounds the ranking bounds the cards.</li>
          <li><strong>Every cost is stated, not just the survival one.</strong> A combination that buys a larger pot with a worse bad case or a higher lifetime tax bill says so on the card.</li>
        </ul>
        <p className="text-xs text-slate-600 leading-relaxed">Measured across the same 420 households, some alternative with a real difference exists for 83% of them, most often a larger pot (70%) or a smaller tax bill (41%), and rarely one on bridge risk (under 1%). The other 17% are told there is no trade-off to make, which is the correct answer for their plan.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">If you rank the priorities yourself</h3>
        <p className="text-xs text-slate-600 leading-relaxed">Under <strong>Advanced</strong> the full ranking is still there for anyone who genuinely has an order. The list is worked down in order: your first priority narrows the field to the settings that are best on it; the second then chooses among <em>those</em>, and so on. A lower priority can only ever break a near-tie on the ones above it, so ranking something first genuinely protects it &mdash; and if you promote the pot or the bequest above survival, you are telling the model you would accept a materially higher chance of running dry in exchange, and it will do exactly that, up to the {E.MAX_SURVIVAL_SACRIFICE_PTS}-point limit. <strong>Balance them all</strong> weighs every priority together instead, so a modest gain in several can outweigh a small loss in one. Whichever you use, the trade-off cards are always priced against the survival-first recommendation, so a card means the same thing every time it appears.</p>
        <p className="text-xs text-slate-600 leading-relaxed">&quot;Near-tie&quot; needs a number, or the top priority would decide everything, since exact ties are rare. The rate threshold is deliberately tighter than the money one: survival is already a probability, so three points of it (90% down to 87%) is a much larger concession than 3% of a pot. It is a tight tolerance rather than a generous one, and simulation sampling can occasionally put two runs of the same plan on opposite sides of it &mdash; the search then settles on a similarly good combination rather than the identical one, never a materially worse one.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">What each priority is, and which policy it pushes towards</h3>
        <div tabIndex={0} className="overflow-x-auto">
          <table className="w-full text-left text-[11px] border-collapse">
            <thead><tr className="border-b border-slate-200 text-slate-500 font-semibold"><th className="pb-1.5 pr-3">Priority</th><th className="pb-1.5 pr-3">What it measures</th><th className="pb-1.5">Why it favours the policy it does</th></tr></thead>
            <tbody className="divide-y divide-slate-100">
              {E.PRIORITY_KEYS.map(k => (
                <tr key={k} className="align-top">
                  <td className="py-1.5 pr-3 font-bold text-slate-800">{E.PRIORITY_METRICS[k].label}</td>
                  <td className="py-1.5 pr-3 text-slate-600">{E.PRIORITY_METRICS[k].why}</td>
                  <td className="py-1.5 text-slate-600">{E.PRIORITY_METRICS[k].serves}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">What this does not yet cover</h3>
        <p className="text-xs text-slate-600 leading-relaxed">Two priorities people legitimately hold are not on the list, because the model cannot yet measure them honestly. <strong>Access before pension age</strong> &mdash; a policy that drains ISAs early leaves you richer on paper but with wealth locked until pension age and taxable to reach &mdash; needs a measure of accessible wealth the engine does not currently report. <strong>Simplicity</strong> is real too: Sequential needs no annual bracket management, and that is worth something in effort and in avoided mistakes, but it is not a number this model can produce.</p>
        </PhoneCollapse>
      </div>

      <div id="doc-cgt" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><Wallet className="w-4 h-4 text-blue-600" /> Capital Gains Tax on Other Investments (GIA)</h2>
        <p className="text-xs text-slate-600 leading-relaxed">Pensions and ISAs shelter growth, but a general investment account does not. When CGT is switched on in Config, the engine tracks the <strong>cost basis</strong> of each person's GIA and charges tax on gains as they are realised.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Growth is not taxed until you sell</h3>
        <p className="text-xs text-slate-600 leading-relaxed">Holding costs nothing. Money paid in is added at cost; growth raises the value without raising the cost, so the unrealised gain builds up untaxed. Tax is only triggered by a disposal: funding your spending, paying a one-off cost, or moving money out under a staged deposit. Each disposal is treated as selling a slice of the whole holding, so the gain is the same proportion of the sale as the unrealised gain is of the pot.</p>
        <p className="text-xs text-slate-600 leading-relaxed">Example: a {formatGBP(100000)} GIA holding {formatGBP(40000)} of gain is 40% gain. Selling {formatGBP(10000)} realises {formatGBP(4000)}; the remaining {formatGBP(3000)} exemption leaves {formatGBP(1000)} taxable, so the bill is {formatGBP(180)} at the basic rate.</p>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Rates and allowances</h3>
        <ul className="list-disc pl-5 text-xs text-slate-600 space-y-1">
          <li>Each person has a {formatGBP(P.cgtAnnualExempt)} annual exempt amount. If you have already realised gains this tax year, enter them in Plan Inputs so the current year's exemption is reduced; leaving it blank assumes the full allowance is available.</li>
          <li>Gains stack on top of that year's income: the part falling in your remaining basic-rate band is taxed at {Math.round(P.cgtBasicRate * 100)}%, anything above at {Math.round(P.cgtHigherRate * 100)}%.</li>
          <li>The bill is settled from cash, then the GIA, then ISAs, then an accessible pension. This is the same order used for one-off costs. Selling to pay the bill realises a little more gain, which is carried into the next year, mirroring the fact that CGT is due the January after the tax year.</li>
        </ul>

        <h3 className="text-sm font-semibold text-slate-800 pt-1">Setting your opening position</h3>
        <p className="text-xs text-slate-600 leading-relaxed">The "of which unrealised gain" figure on the GIA row tells the engine how much of today's balance is profit. Left blank, the balance is treated as entirely cost, so only future growth is ever taxed, which may provide too much weight to GIA. If you hold long-standing investments with a large embedded gain, enter it, or the model will understate your tax.</p>

        <p className="text-xs text-slate-500 leading-relaxed"><strong>Deliberate omissions:</strong> gains are wiped by the uplift on death, so nothing is charged on whatever remains at the terminal age. This is a real reason to spend other wrappers first. Dividends and interest inside the GIA are not modelled separately, share pooling and the 30-day rule are ignored, and the exempt amount and rates are held flat in real terms at the Config figures.</p>
        </PhoneCollapse>
      </div>

      <div id="doc-one-offs" className="bg-surface border border-slate-200/90 p-5 rounded-xl space-y-3">
        <PhoneCollapse isPhone={isPhone}>
        <h2 className="text-base font-semibold text-slate-900 flex items-center gap-2"><Coins className="w-4 h-4 text-blue-600" /> One-Off Cost Liquidation Hierarchy</h2>
        <p className="text-xs text-slate-600 leading-relaxed">When a one-off capital cost is scheduled, the engine liquidates assets in this order:</p>
        <ol className="list-decimal pl-5 text-xs text-slate-600 space-y-1">
          <li><strong>Cash Savings</strong> (both owners), then <strong>Other Investments (GIA)</strong>, then <strong>Stocks &amp; Shares ISAs</strong>.</li>
          <li><strong>Pensions</strong>, but only for an owner who has reached the access age ({nmpa}). If the cost still cannot be met, the year is flagged as a shortfall, or a pre-SIPP access gap when pension money existed but was locked.</li>
        </ol>
        <p className="text-xs text-slate-500">Known simplifications: state pension is held flat in real terms (no triple-lock uplift), tax thresholds and allowances are held flat in real terms, and the death of a partner is not modelled.</p>
        <p className="text-xs text-slate-500 leading-relaxed"><strong>Pension allowance limitations.</strong> The model assumes you have <strong>not</strong> yet flexibly accessed a pension, because it is built for planning towards retirement rather than for someone already drawing an income. If you have already taken taxable pension income, your annual allowance is already {formatGBP(P.mpaaLimit)} and the projection will overstate how much you can contribute until the year it starts drawing. Carry forward is also worked out independently for each year rather than being consumed as it is used, so several large staged deposits in overlapping years could each count the same unused allowance. Neither the tapered annual allowance for high earners nor annual allowance charges themselves are modelled.</p>
        </PhoneCollapse>
      </div>
    </div>
  );
}
